### PR TITLE
Select best method only once at module load time

### LINKED ISSUE #8: new Buffer() is deprecated
... and even removed in Node 8.0

Use:
```js
Buffer.from()
```

### PR DESCRIPTION
**Pull request by mk-pmb**
I couldn't find browser tests, so I at least jslinted it.
Error message adjusted to fit MSIE 4 and 6.
Also fixes #8.

### CODE REVIEW

**Comment by mk-pmb** [comment]
The other thread looks like you like the PR, so is there anything I can help to facilitate the merge? Shall I bump the version for example?

**Comment by dy** [comment]
@mk-pmb what is the actual reason for `Buffer.from` constructor here? That bloats up the package size up to 55kb instead of 3kb :worried:.

**Comment by mk-pmb** [comment]
In node, using the Buffer constructor has been deprecated for security reasons. Thinking again however, browsers are expected to deal with the most dangerous code in a safe way, and to deal with ancient code in a way that degrades gracefully, so we might actually get away with `new Buffer()` in the browser version.
I'll downgrade that part and hope this fixes the package size blowup. Is there an easy way I can measure that myself?

PS: The problem with the old API is that we don't specify whether we meant to trade security for speed, i.e. whether our program shall perform the additional work of clearing away old buffer contents that may contain secret/private data that could be exposed when we share the buffer with other programs or a network. For a browser, it should be irrelevant what we meant in this choice, as there is only one safe decision.

**Comment by mk-pmb** [comment]
PR is updated.

**Comment by mk-pmb** [comment]
Updated again because I forgot to lint first.

**Comment by dy** [comment]
@mk-pmb why not just `module.exports = window.atob` for browser? It is well-supported since long ago. 
The easy way to test the size is `browserify browser-atob.js | size`, if you have [browserify](https://npmjs.org/package/browserify) and [size](https://npmjs.org/package/size) installed

**Comment by mk-pmb** [comment]
> why not just module.exports = window.atob for browser?

For browsers that support window.atob, that's the expected effective behavior for this PR's code.

> It is well-supported since long ago.

I lack the overview of browser quirks and usage statistics to decide about removing compatibility fallbacks. If you convince the maintainer, I'll happily adapt the source.

As for browserify, or any other method of repackaging this package for browsers, the result should be just the code from `browser-atob.js` + some minimal overhead for a wrapper. Even smaller if you minify it, of course. Do you have the 3kb file online so I can compare and see what goes wrong?

**Comment by dy** [comment]
@mk-pmb here is the analog https://github.com/hughsk/atob-lite

**Comment by mk-pmb** [comment]
`atob-lite` doesn't include the iOS web worker functions, so I can't see how it can help me research the reasons for blow-up in browserified size for this module.
If your concern is about them, please make another issue thread where you suggest to no longer ship them.
This PR is just about a change in implementation, while preserving all features and capabilities.

If you find a way to reproduce the old 3kb file, or find a backup of it, I'll try and research what went wrong. For now, all I have for comparison is the current master branch, and compared to that, my PR seems to only add 443 bytes when bundled:

```
$ browserify browser-atob.master.js | wc --bytes
53332
$ browserify browser-atob.js | wc --bytes
53775
$ % 53775-53332
443
```

A lot of them are comments and similar stuff, so it boils down to only 75 additional bytes when you compare it minified:

```
$ browserify browser-atob.master.js | uglify-js --compress --mangle | wc --bytes
22122
$ browserify browser-atob.js | uglify-js --compress --mangle | wc --bytes
22197
$ % 22197-22122
75
```

I think 75 bytes are a fair price for saving lots of feature detection at runtime. Actually, this inspires me to tune performance even more, by aliasing some functions. First I'll have to verify some other bugs though, to avoid optimizing redundant code.

**Comment by greedyallay** [comment]
What mf came up with this it is preventing my site from fucking functioning

**Comment by mk-pmb** [comment]
If a module prevents your site from functioning, the easiest solution is usually to omit that module. (If you expect better help, avoid insults and instead try to help us help you.)

**Comment by coolaj86** [comment]
This module hasn't been updated in years, and if it ever does, it'll because I have my leftpad or Marak or Fight Club moment.

If something is causing your stuff to break, it's one of the bundler systems (e.g. Vite, Nuxt, Next, Rollup, Rolldown, etc) introduced a new bug that imported the module incorrectly in one of your dependencies, so you'll have to go open the issue over there.
(and the real bug is anyone using this at all - it was created a decade ago to solve issue caused by political infighting among committees, not to solve an actual technical challenge)

This is incredibly fragile and any attempt to make it work for one person will absolutely cause it to break for thousands of others. See: <https://github.com/jojobyte/browser-import-rabbit-hole>. (and if you don't understand the insanity of that... count your blessings)

I share your angst, but I'm not the to blame, nor the one who can help you.

Software is eating the world... ™

**Comment by coolaj86** [comment]
hasn't*

**Comment by mk-pmb** [comment]
Maybe we should update the "Discussion: (link to this issue)" line to instead say that this module is deprecated and anyone using it should please stop to do so.

**Comment by coolaj86** [comment]
I'm not touching it. The systems using this are going to break any day all on their own.

Even updating it to publish a comment will trigger some sleeping build system to wake up and erupt.


This (and btoa) are unfortunately downloaded something like 50 million times a month.

**Pull request merged**
